Traceback (most recent call last):
<<<<<<< HEAD
  File "/opt/anaconda3/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/opt/anaconda3/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/opt/anaconda3/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
=======
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 56, in single_nb_execution
    record_timing=False,
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 1077, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 527, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 822, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/jacobkoehler/opt/anaconda3/lib/python3.7/site-packages/nbclient/client.py", line 730, in _check_raise_for_error
>>>>>>> d1a3331c4bb70eb63f6c667c0eee992efd40248b
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
cpi.groupby('Year').mean().plot()
plt.title('CPI by Year: 1935 - 2020');
------------------

<<<<<<< HEAD
[0;31m---------------------------------------------------------------------------[0m
[0;31mTypeError[0m                                 Traceback (most recent call last)
=======
[0;31m-------------------------------------------------------------------[0m
[0;31mTypeError[0m                         Traceback (most recent call last)
>>>>>>> d1a3331c4bb70eb63f6c667c0eee992efd40248b
[0;32m<ipython-input-16-cd37f3effdc1>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mcpi[0m[0;34m.[0m[0mgroupby[0m[0;34m([0m[0;34m'Year'[0m[0;34m)[0m[0;34m.[0m[0mmean[0m[0;34m([0m[0;34m)[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m      2[0m [0mplt[0m[0;34m.[0m[0mtitle[0m[0;34m([0m[0;34m'CPI by Year: 1935 - 2020'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m

<<<<<<< HEAD
[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_core.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
=======
[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_core.py[0m in [0;36m__call__[0;34m(self, *args, **kwargs)[0m
>>>>>>> d1a3331c4bb70eb63f6c667c0eee992efd40248b
[1;32m    970[0m                     [0mdata[0m[0;34m.[0m[0mcolumns[0m [0;34m=[0m [0mlabel_name[0m[0;34m[0m[0;34m[0m[0m
[1;32m    971[0m [0;34m[0m[0m
[0;32m--> 972[0;31m         [0;32mreturn[0m [0mplot_backend[0m[0;34m.[0m[0mplot[0m[0;34m([0m[0mdata[0m[0;34m,[0m [0mkind[0m[0;34m=[0m[0mkind[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    973[0m [0;34m[0m[0m
[1;32m    974[0m     [0m__call__[0m[0;34m.[0m[0m__doc__[0m [0;34m=[0m [0m__doc__[0m[0;34m[0m[0;34m[0m[0m

<<<<<<< HEAD
[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/__init__.py[0m in [0;36mplot[0;34m(data, kind, **kwargs)[0m
=======
[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/__init__.py[0m in [0;36mplot[0;34m(data, kind, **kwargs)[0m
>>>>>>> d1a3331c4bb70eb63f6c667c0eee992efd40248b
[1;32m     69[0m             [0mkwargs[0m[0;34m[[0m[0;34m"ax"[0m[0;34m][0m [0;34m=[0m [0mgetattr[0m[0;34m([0m[0max[0m[0;34m,[0m [0;34m"left_ax"[0m[0;34m,[0m [0max[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     70[0m     [0mplot_obj[0m [0;34m=[0m [0mPLOT_CLASSES[0m[0;34m[[0m[0mkind[0m[0;34m][0m[0;34m([0m[0mdata[0m[0;34m,[0m [0;34m**[0m[0mkwargs[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m---> 71[0;31m     [0mplot_obj[0m[0;34m.[0m[0mgenerate[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     72[0m     [0mplot_obj[0m[0;34m.[0m[0mdraw[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m     73[0m     [0;32mreturn[0m [0mplot_obj[0m[0;34m.[0m[0mresult[0m[0;34m[0m[0;34m[0m[0m

<<<<<<< HEAD
[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36mgenerate[0;34m(self)[0m
[1;32m    325[0m     [0;32mdef[0m [0mgenerate[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    326[0m         [0mself[0m[0;34m.[0m[0m_args_adjust[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 327[0;31m         [0mself[0m[0;34m.[0m[0m_compute_plot_data[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    328[0m         [0mself[0m[0;34m.[0m[0m_setup_subplots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    329[0m         [0mself[0m[0;34m.[0m[0m_make_plot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m/opt/anaconda3/lib/python3.8/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36m_compute_plot_data[0;34m(self)[0m
[1;32m    504[0m         [0;31m# no non-numeric frames or series allowed[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    505[0m         [0;32mif[0m [0mis_empty[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 506[0;31m             [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34m"no numeric data to plot"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    507[0m [0;34m[0m[0m
[1;32m    508[0m         [0mself[0m[0;34m.[0m[0mdata[0m [0;34m=[0m [0mnumeric_data[0m[0;34m.[0m[0mapply[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_convert_to_ndarray[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
=======
[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36mgenerate[0;34m(self)[0m
[1;32m    284[0m     [0;32mdef[0m [0mgenerate[0m[0;34m([0m[0mself[0m[0;34m)[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[1;32m    285[0m         [0mself[0m[0;34m.[0m[0m_args_adjust[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 286[0;31m         [0mself[0m[0;34m.[0m[0m_compute_plot_data[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    287[0m         [0mself[0m[0;34m.[0m[0m_setup_subplots[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[1;32m    288[0m         [0mself[0m[0;34m.[0m[0m_make_plot[0m[0;34m([0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m

[0;32m~/opt/anaconda3/lib/python3.7/site-packages/pandas/plotting/_matplotlib/core.py[0m in [0;36m_compute_plot_data[0;34m(self)[0m
[1;32m    451[0m         [0;31m# no non-numeric frames or series allowed[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m    452[0m         [0;32mif[0m [0mis_empty[0m[0;34m:[0m[0;34m[0m[0;34m[0m[0m
[0;32m--> 453[0;31m             [0;32mraise[0m [0mTypeError[0m[0;34m([0m[0;34m"no numeric data to plot"[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m    454[0m [0;34m[0m[0m
[1;32m    455[0m         [0mself[0m[0;34m.[0m[0mdata[0m [0;34m=[0m [0mnumeric_data[0m[0;34m.[0m[0mapply[0m[0;34m([0m[0mself[0m[0;34m.[0m[0m_convert_to_ndarray[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
>>>>>>> d1a3331c4bb70eb63f6c667c0eee992efd40248b

[0;31mTypeError[0m: no numeric data to plot
TypeError: no numeric data to plot

